[package]
name = "freya-router"
authors = ["Jonathan Kelley", "Evan Almloff", "Marc Espín <mespinsanz@gmail.com>"]
version = "0.3.0"
edition = "2021"
description = "Router management for Freya apps"
license = "MIT"
repository = "https://github.com/marc2332/freya/"
keywords = ["gui", "ui", "desktop", "skia", "dioxus"]

[dependencies]
dioxus-lib = { workspace = true }
freya-router-macro = { workspace = true }
freya-hooks = { workspace = true }
freya-elements = { workspace = true }

tracing = { workspace = true }
urlencoding = "2.1.3"
url = "2.5.4"
rustversion = "1.0.21"

